### ISSUE TITLE
小屏的时候setScaleType貌似无效？

### ISSUE THREAD

**Issue by cikichen** [tcking/GiraffePlayer#1]
小屏的时候setScaleType貌似无效？

**Comment by tcking** [comment]
双击播放画面时会切换ScaleType，看是否生效

**Comment by lileichinasoft** [comment]
建议：可以加一个双击屏幕暂停播放的处理

**Comment by tcking** [comment]
@lileichinasoft 双击暂停并非普遍需求，类似的需求可以通过修改PlayerGestureListener来实现
