### ISSUE TITLE
小窗播放转全屏播放，布局必须是linearlayout的，否则播放器不会占全屏

### ISSUE THREAD

**Issue by pickyourself** [tcking/GiraffePlayer#2]
小窗播放转全屏播放，布局必须是linearlayout的，否则播放器不会占全屏

**Comment by tcking** [comment]
横屏是会尝试修改id为`app_video_box`的高度为屏幕的高度，`IjkVideoView`会充满整个`app_video_box`以达到全屏播放的效果，只要外层的`ViewGroup`能满足这个要求应该就是可以的。你也可以尝试修改下`activity_main.xml`的root为`RelativeLayout`并将giraffe_player放到最后一个子元素，也是可以全屏的
