### ISSUE TITLE
m3u suport?

### ISSUE THREAD

**Issue by diaconuliviu85** [tcking/GiraffePlayer#20]
Hello

What can I do to use and M3U?
at the moment M3U crashes.

Please do not forget to add more portions api for resolution and progress would be perfect.

**Comment by tcking** [comment]
it support HLS(m3u8),is the same thing? could you give more info about that such like stack trace or test url. (the player base on [ijkplayer](https://github.com/Bilibili/ijkplayer) )

I will add some callback api in a few days.
what kind of apis do you  want ? create issues is welcome

**Comment by diaconuliviu85** [comment]
just like I promised I started to go with Dpad change, remote.
nexus remote control player, pause play center.
left and right to either + time - time viewing of video.
and up and down to change the screen 16: 9 etc.
I still need api to change resolution, to be put on the button up or down.
A climb to the changes to see them and you can modify and together.

**Comment by diaconuliviu85** [comment]
Image  android Tv
[url=http://postimg.org/image/amf5fhorb/][img]http://s7.postimg.org/amf5fhorb/dddd.png[/img][/url]

[url=http://postimg.org/image/ncjdskwpj/][img]http://s7.postimg.org/ncjdskwpj/ddddsdsdd.png[/img][/url]

I compiled the full version of "lib" goes perfectly .avi, RTMP remains in question if RTMP has token or swf not working. suspect is a erroare somewhere.
lib .so are large forces 45 mb. but absolutely worth orce view format.
idea for android tv, I add just Dpad control. to be something different.
