### ISSUE TITLE
横竖屏切换问题

### ISSUE THREAD

**Issue by CaesarZhao** [tcking/GiraffePlayer#24]
我有一个比较复杂的布局，在横竖屏切换的时候播放器无法全屏显示，播放的空间是放在viewpage里面的。不知道怎么解决这个问题。非常感谢。

![image](http://cdn.sinacloud.net/ford-file1247/Screenshot_20160330-182631.png?KID=sina,166kb271Z2dXodznJe0k&Expires=1459337807&ssig=FUEilPcgU9)

![image](http://cdn.sinacloud.net/ford-file1247/Screenshot_20160330-182621.png?KID=sina,166kb271Z2dXodznJe0k&Expires=1459337804&ssig=qBX10bX3R9)

**Comment by tcking** [comment]
先确activity的onConfigChanged回调是否调用了player对应的方法，另外就是在横屏时考虑把非视频部分的view都gone掉

**Comment by CaesarZhao** [comment]
非常感谢 完美
