### ISSUE TITLE
OpenSSL: https protocol not found

### ISSUE THREAD

**Issue by migueltarga** [tcking/GiraffePlayer#25]
Im using the latest version and still getting:

"https protocol not found recompile FFmpeg with openssl, gnutls,  or securetransport enabled."

even after this: https://github.com/tcking/GiraffePlayer/releases/tag/0.3

how can I fix it?

**Comment by tcking** [comment]
the FFmpeg is compile with openssl , is the example works fine on your devices?

**Comment by migueltarga** [comment]
I had to recompile it with openssl, and now it work.   Do you want me to do PR?

**Comment by Vaporexpress** [comment]
Hi. works fine with openssl but openssl version addresses vulnerabilities (See https://support.google.com/faqs/answer/6376725 ).

**Comment by diaconuliviu85** [comment]
Download this , and change you libs so .
this libs is compiled from openssl 1.1 prev4, 
https://mega.nz/#F!sF9mWSRa

**Comment by migueltarga** [comment]
Awesome, 
to compile to other versions just change this line:
https://github.com/Bilibili/ijkplayer/blob/master/init-android-openssl.sh#L21

**Comment by Vaporexpress** [comment]
@diaconuliviu85 Your Mega link ask me a Decryption key to download.
@migueltarga OK, but I'm on a Windows box (with Cygwin64) and I can compile only ffmpeg with some tweaks. When I try to compile OpenSSL I'm get stuck into errors.
Thankx, but I need so libraries ffmpeg + openssl 1.02f/1.01r or higher.

**Comment by migueltarga** [comment]
Made a ripo to share with you https://github.com/migueltarga/ffmpeg-openssl

Now Im wondering how to add librtmp to ffmpeg, if anybody knows

**Comment by Vaporexpress** [comment]
@migueltarga Don't work your libs on GiraffePlayer:
https://gist.github.com/Vaporexpress/1aaee6b291594a3f48cd1ef8aeffb606

**Comment by migueltarga** [comment]
Its working fine in my GiraffePlayer build, I just replaced with this ones last night.
I will double check it once I get home, and I let you know.

**Comment by diaconuliviu85** [comment]
https://mega.nz/#F!sF9mWSRa!LlswlzCOQMwHn1rY_hRobg

this is work , and the lib is version mega(best libs ijkplayer)

**Comment by Vaporexpress** [comment]
@diaconuliviu85 Same as migueltarga libs: "https protocol not found".
If I check the apk with:  unzip -p GiraffeApp.apk | strings | grep "OpenSSL" 
Your libs return nothing and with migueltarga libs return "OpenSSL 1.0.2g  1 Mar 2016" which is OK although later shows the same error with a youtube https link.

**Comment by diaconuliviu85** [comment]
My lib is openssl 1.1 prev4 and is work fine from google play. For unzip is returned GSM_Openssl . For my is worked for fixed this vulnerabilities

**Comment by tcking** [comment]
OpenSSL upgrade to 1.0.2g via [0.6] (https://github.com/tcking/GiraffePlayer/releases/tag/0.6)
