### ISSUE TITLE
.avi not work

### ISSUE THREAD

**Issue by diaconuliviu85** [tcking/GiraffePlayer#3]
very good this player. but not going to .avi?
and another question
how can I do to make zoom? there do not understand the explanation, can say in English?

**Comment by tcking** [comment]
can u give the video url？thank u.
double click video view will toggle scale type then u will find which you want

**Comment by diaconuliviu85** [comment]
http://www.videostudio.co.uk/cinedemo.avi this video sample and more avi videos.

**Comment by tcking** [comment]
the video codec is dvsd,however the GiraffePlayer base on ijkplayer only support H264

**Comment by diaconuliviu85** [comment]
Thanks for the reply.
