### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by aii1991** [tcking/GiraffePlayer#32]
发现使用giraffeplayer会有内存泄漏.
不断打开和finish播放页面,内存不断提高无法被回收

**Comment by tcking** [comment]
run的是sample还是集成到自己的app中？

**Comment by aii1991** [comment]
sample和集成都会  发现原因了  

- GiraffePlayer   onDestroy中没用调用handler.removeCallbacksAndMessages(null);导致handler不能被释放从而导致activity不能被回收

**Comment by tcking** [comment]
是的，经过检查漏了remove `MESSAGE_SHOW_PROGRESS`，采用`removeCallbacksAndMessages(null)`的方式更彻底

**Comment by tcking** [comment]
fix via [0.8](https://github.com/tcking/GiraffePlayer/releases/tag/0.8)
