### ISSUE TITLE
"Protocol not found" for YouTube link.

### ISSUE THREAD

**Issue by vipulpurohit** [tcking/GiraffePlayer#4]
Hello,
FIrst of all thanks for this amazing library.
I'm trying to play YouTube link https://www.youtube.com/watch?v=ITEXG22Y0MY in the player but I'm getting "Protocol not found" error in ijkPlayer.
I know this is openssl issue and I think we need to compile ijkPlayer with openssl.
I was trying to fix it myself but I'm on windows machine and don't have any linux or Mac to compile ijkPlayer.
Can you please fix this issue so GiraffePlayer can play youtube link also.

Thanks

**Comment by tcking** [comment]
I try to compile it with openssl,but some errors occured，I will try it later.

**Comment by tcking** [comment]
https://github.com/tcking/GiraffePlayer/releases/tag/0.3
