### ISSUE TITLE
怎么设置m3u8的清晰度

### ISSUE THREAD

**Issue by gityan** [tcking/GiraffePlayer#46]
播放一个m3u8的地址，包含多个清晰度。在VLC播放时会选择最清晰的。但是用GiraffePlayer会默认选择分辨率最低的。请问如何可以设置清晰度呢。

**Comment by tcking** [comment]
这个需要修改ijkplayer的代码来选择不同的流了，目前是没有提供对外的接口来选择

**Comment by gityan** [comment]
这样啊 好吧 3q～
