### ISSUE TITLE
Not full screen in TV Box

### ISSUE THREAD

**Issue by HackJoues** [tcking/GiraffePlayer#83]
Hello, how i can get the fullscreen of this app in a Tv Box?

**Comment by tcking** [comment]
try this: `                    GiraffePlayerActivity.configPlayer(MainActivity.this).setTitle(url).setFullScreenOnly(true).play(url);
`

**Comment by HackJoues** [comment]
Where do I put this code?

**Comment by HackJoues** [comment]
Fixed!
