### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by Khoosham** [tcking/GiraffePlayer#92]
is there a way to set the video quality like 360p, 420p or 720p? Thank you.

**Comment by tcking** [comment]
the quality depends on your video stream,u can provide different url for each quality

**Comment by Khoosham** [comment]
the problem is that its a m3u8 url
https://xxxxxxxx.com/live/live.m3u8

the video bitrate is only avaialble when the streams start to play i think idk how to get that value
i can see it in the debug log. it would be nice if a smal menu can be pop up and choose quality

**Comment by Khoosham** [comment]
i move to exoplayer which seems a better option closing that issue :)
